# TODO: move the uncategorized variables into a section of some sort
# TODO: comment out the variables and what do they mean

prefix = "%"
channel_id = [935543814335107152, 857822603292442674, 857816882899583006, 857816615273889813]

name = "Holotard"
max_length = 32768
response_probability = 0.02

[Inference]
length = 32
top_p = 1
temperature = 0.9

[Model]
layers = 28
d_model = 4096
n_heads = 16
n_vocab = 50400
norm = "layernorm"
pe = "rotary"
pe_rotary_dims = 64
seq = 2048
cores_per_replica = 8
per_replica_batch = 1